### ISSUE TITLE
Documentation suggestion 

### ISSUE THREAD

**Issue by michaelairola** [chaos-lang/chaos-lang.org#2]
Really small thing, but I figured you guys might appreciate if I point it out. [https://github.com/chaos-lang/chaos-lang.org/blob/master/website/docs/04_primitive-data-types.md](url) In the Number section, I think you meant to use "number" to define the second variable instead of "num." That is all

**Comment by mertyildiran** [comment]
@michaelairola changed it with https://github.com/chaos-lang/chaos-lang.org/commit/db8bfde7d5a7635a31e4f5cdb5f607708b915e27 Thank you so much for noticing it! :blush:
