### ISSUE TITLE
Question: How to generate html from your site?

### ISSUE THREAD

**Issue by ghost** [chaos-lang/chaos-lang.org#5]
@imdpkj @mertyildiran @pluckyporcupine @colvin
 I read docusaurus documentation, but I can’t understand how to build it and generate html.

**Comment by mertyildiran** [comment]
@lewek you have to run `yarn install` and `yarn start` in `website/` directory. Then visit http://localhost:3000/

The documentation is located under `[website/docs/](https://github.com/chaos-lang/chaos-lang.org/tree/master/website/docs)` directory in Markdown format.
