### ISSUE TITLE
Simple question about feature icons.

### ISSUE THREAD

**Issue by enty8080** [chaos-lang/chaos-lang.org#6]
@imdpkj @mertyildiran @pluckyporcupine @colvin 

Feature icons are very small, I looked in your code for a part that is responsible for their size, but I could not find it. Can you tell me how to change their size if possible.

Thanks.

**Comment by ghost** [comment]
@enty8080 Try searching on docusarus.

**Comment by mertyildiran** [comment]
@enty8080 the component used there is coming from `website/node_modules/docusaurus/lib/core/GridBlock.js` and I'm not sure where the styling is defined exactly. As @lewek said you should rather ask this question to [facebook/docusaurus](https://github.com/facebook/docusaurus).

If you would like to override the styling then you can do it in [here](https://github.com/chaos-lang/chaos-lang.org/blob/0274ec79fb5cc18cae787d10ae1ef4596e8de1e4/website/pages/en/index.js#L93-L104).
